# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tim/workspace/cg-utils

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tim/workspace/cg-utils

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tim/workspace/cg-utils/CMakeFiles /home/tim/workspace/cg-utils/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tim/workspace/cg-utils/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cgutils

# Build rule for target.
cgutils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cgutils
.PHONY : cgutils

# fast build rule for target.
cgutils/fast:
	$(MAKE) -f CMakeFiles/cgutils.dir/build.make CMakeFiles/cgutils.dir/build
.PHONY : cgutils/fast

src/aabb.o: src/aabb.cpp.o
.PHONY : src/aabb.o

# target to build an object file
src/aabb.cpp.o:
	$(MAKE) -f CMakeFiles/cgutils.dir/build.make CMakeFiles/cgutils.dir/src/aabb.cpp.o
.PHONY : src/aabb.cpp.o

src/aabb.i: src/aabb.cpp.i
.PHONY : src/aabb.i

# target to preprocess a source file
src/aabb.cpp.i:
	$(MAKE) -f CMakeFiles/cgutils.dir/build.make CMakeFiles/cgutils.dir/src/aabb.cpp.i
.PHONY : src/aabb.cpp.i

src/aabb.s: src/aabb.cpp.s
.PHONY : src/aabb.s

# target to generate assembly for a file
src/aabb.cpp.s:
	$(MAKE) -f CMakeFiles/cgutils.dir/build.make CMakeFiles/cgutils.dir/src/aabb.cpp.s
.PHONY : src/aabb.cpp.s

src/camera.o: src/camera.cpp.o
.PHONY : src/camera.o

# target to build an object file
src/camera.cpp.o:
	$(MAKE) -f CMakeFiles/cgutils.dir/build.make CMakeFiles/cgutils.dir/src/camera.cpp.o
.PHONY : src/camera.cpp.o

src/camera.i: src/camera.cpp.i
.PHONY : src/camera.i

# target to preprocess a source file
src/camera.cpp.i:
	$(MAKE) -f CMakeFiles/cgutils.dir/build.make CMakeFiles/cgutils.dir/src/camera.cpp.i
.PHONY : src/camera.cpp.i

src/camera.s: src/camera.cpp.s
.PHONY : src/camera.s

# target to generate assembly for a file
src/camera.cpp.s:
	$(MAKE) -f CMakeFiles/cgutils.dir/build.make CMakeFiles/cgutils.dir/src/camera.cpp.s
.PHONY : src/camera.cpp.s

src/common.o: src/common.cpp.o
.PHONY : src/common.o

# target to build an object file
src/common.cpp.o:
	$(MAKE) -f CMakeFiles/cgutils.dir/build.make CMakeFiles/cgutils.dir/src/common.cpp.o
.PHONY : src/common.cpp.o

src/common.i: src/common.cpp.i
.PHONY : src/common.i

# target to preprocess a source file
src/common.cpp.i:
	$(MAKE) -f CMakeFiles/cgutils.dir/build.make CMakeFiles/cgutils.dir/src/common.cpp.i
.PHONY : src/common.cpp.i

src/common.s: src/common.cpp.s
.PHONY : src/common.s

# target to generate assembly for a file
src/common.cpp.s:
	$(MAKE) -f CMakeFiles/cgutils.dir/build.make CMakeFiles/cgutils.dir/src/common.cpp.s
.PHONY : src/common.cpp.s

src/entity.o: src/entity.cpp.o
.PHONY : src/entity.o

# target to build an object file
src/entity.cpp.o:
	$(MAKE) -f CMakeFiles/cgutils.dir/build.make CMakeFiles/cgutils.dir/src/entity.cpp.o
.PHONY : src/entity.cpp.o

src/entity.i: src/entity.cpp.i
.PHONY : src/entity.i

# target to preprocess a source file
src/entity.cpp.i:
	$(MAKE) -f CMakeFiles/cgutils.dir/build.make CMakeFiles/cgutils.dir/src/entity.cpp.i
.PHONY : src/entity.cpp.i

src/entity.s: src/entity.cpp.s
.PHONY : src/entity.s

# target to generate assembly for a file
src/entity.cpp.s:
	$(MAKE) -f CMakeFiles/cgutils.dir/build.make CMakeFiles/cgutils.dir/src/entity.cpp.s
.PHONY : src/entity.cpp.s

src/light.o: src/light.cpp.o
.PHONY : src/light.o

# target to build an object file
src/light.cpp.o:
	$(MAKE) -f CMakeFiles/cgutils.dir/build.make CMakeFiles/cgutils.dir/src/light.cpp.o
.PHONY : src/light.cpp.o

src/light.i: src/light.cpp.i
.PHONY : src/light.i

# target to preprocess a source file
src/light.cpp.i:
	$(MAKE) -f CMakeFiles/cgutils.dir/build.make CMakeFiles/cgutils.dir/src/light.cpp.i
.PHONY : src/light.cpp.i

src/light.s: src/light.cpp.s
.PHONY : src/light.s

# target to generate assembly for a file
src/light.cpp.s:
	$(MAKE) -f CMakeFiles/cgutils.dir/build.make CMakeFiles/cgutils.dir/src/light.cpp.s
.PHONY : src/light.cpp.s

src/material.o: src/material.cpp.o
.PHONY : src/material.o

# target to build an object file
src/material.cpp.o:
	$(MAKE) -f CMakeFiles/cgutils.dir/build.make CMakeFiles/cgutils.dir/src/material.cpp.o
.PHONY : src/material.cpp.o

src/material.i: src/material.cpp.i
.PHONY : src/material.i

# target to preprocess a source file
src/material.cpp.i:
	$(MAKE) -f CMakeFiles/cgutils.dir/build.make CMakeFiles/cgutils.dir/src/material.cpp.i
.PHONY : src/material.cpp.i

src/material.s: src/material.cpp.s
.PHONY : src/material.s

# target to generate assembly for a file
src/material.cpp.s:
	$(MAKE) -f CMakeFiles/cgutils.dir/build.make CMakeFiles/cgutils.dir/src/material.cpp.s
.PHONY : src/material.cpp.s

src/mesh.o: src/mesh.cpp.o
.PHONY : src/mesh.o

# target to build an object file
src/mesh.cpp.o:
	$(MAKE) -f CMakeFiles/cgutils.dir/build.make CMakeFiles/cgutils.dir/src/mesh.cpp.o
.PHONY : src/mesh.cpp.o

src/mesh.i: src/mesh.cpp.i
.PHONY : src/mesh.i

# target to preprocess a source file
src/mesh.cpp.i:
	$(MAKE) -f CMakeFiles/cgutils.dir/build.make CMakeFiles/cgutils.dir/src/mesh.cpp.i
.PHONY : src/mesh.cpp.i

src/mesh.s: src/mesh.cpp.s
.PHONY : src/mesh.s

# target to generate assembly for a file
src/mesh.cpp.s:
	$(MAKE) -f CMakeFiles/cgutils.dir/build.make CMakeFiles/cgutils.dir/src/mesh.cpp.s
.PHONY : src/mesh.cpp.s

src/ray.o: src/ray.cpp.o
.PHONY : src/ray.o

# target to build an object file
src/ray.cpp.o:
	$(MAKE) -f CMakeFiles/cgutils.dir/build.make CMakeFiles/cgutils.dir/src/ray.cpp.o
.PHONY : src/ray.cpp.o

src/ray.i: src/ray.cpp.i
.PHONY : src/ray.i

# target to preprocess a source file
src/ray.cpp.i:
	$(MAKE) -f CMakeFiles/cgutils.dir/build.make CMakeFiles/cgutils.dir/src/ray.cpp.i
.PHONY : src/ray.cpp.i

src/ray.s: src/ray.cpp.s
.PHONY : src/ray.s

# target to generate assembly for a file
src/ray.cpp.s:
	$(MAKE) -f CMakeFiles/cgutils.dir/build.make CMakeFiles/cgutils.dir/src/ray.cpp.s
.PHONY : src/ray.cpp.s

src/resources.o: src/resources.cpp.o
.PHONY : src/resources.o

# target to build an object file
src/resources.cpp.o:
	$(MAKE) -f CMakeFiles/cgutils.dir/build.make CMakeFiles/cgutils.dir/src/resources.cpp.o
.PHONY : src/resources.cpp.o

src/resources.i: src/resources.cpp.i
.PHONY : src/resources.i

# target to preprocess a source file
src/resources.cpp.i:
	$(MAKE) -f CMakeFiles/cgutils.dir/build.make CMakeFiles/cgutils.dir/src/resources.cpp.i
.PHONY : src/resources.cpp.i

src/resources.s: src/resources.cpp.s
.PHONY : src/resources.s

# target to generate assembly for a file
src/resources.cpp.s:
	$(MAKE) -f CMakeFiles/cgutils.dir/build.make CMakeFiles/cgutils.dir/src/resources.cpp.s
.PHONY : src/resources.cpp.s

src/rtimage.o: src/rtimage.cpp.o
.PHONY : src/rtimage.o

# target to build an object file
src/rtimage.cpp.o:
	$(MAKE) -f CMakeFiles/cgutils.dir/build.make CMakeFiles/cgutils.dir/src/rtimage.cpp.o
.PHONY : src/rtimage.cpp.o

src/rtimage.i: src/rtimage.cpp.i
.PHONY : src/rtimage.i

# target to preprocess a source file
src/rtimage.cpp.i:
	$(MAKE) -f CMakeFiles/cgutils.dir/build.make CMakeFiles/cgutils.dir/src/rtimage.cpp.i
.PHONY : src/rtimage.cpp.i

src/rtimage.s: src/rtimage.cpp.s
.PHONY : src/rtimage.s

# target to generate assembly for a file
src/rtimage.cpp.s:
	$(MAKE) -f CMakeFiles/cgutils.dir/build.make CMakeFiles/cgutils.dir/src/rtimage.cpp.s
.PHONY : src/rtimage.cpp.s

src/texture.o: src/texture.cpp.o
.PHONY : src/texture.o

# target to build an object file
src/texture.cpp.o:
	$(MAKE) -f CMakeFiles/cgutils.dir/build.make CMakeFiles/cgutils.dir/src/texture.cpp.o
.PHONY : src/texture.cpp.o

src/texture.i: src/texture.cpp.i
.PHONY : src/texture.i

# target to preprocess a source file
src/texture.cpp.i:
	$(MAKE) -f CMakeFiles/cgutils.dir/build.make CMakeFiles/cgutils.dir/src/texture.cpp.i
.PHONY : src/texture.cpp.i

src/texture.s: src/texture.cpp.s
.PHONY : src/texture.s

# target to generate assembly for a file
src/texture.cpp.s:
	$(MAKE) -f CMakeFiles/cgutils.dir/build.make CMakeFiles/cgutils.dir/src/texture.cpp.s
.PHONY : src/texture.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... cgutils"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/aabb.o"
	@echo "... src/aabb.i"
	@echo "... src/aabb.s"
	@echo "... src/camera.o"
	@echo "... src/camera.i"
	@echo "... src/camera.s"
	@echo "... src/common.o"
	@echo "... src/common.i"
	@echo "... src/common.s"
	@echo "... src/entity.o"
	@echo "... src/entity.i"
	@echo "... src/entity.s"
	@echo "... src/light.o"
	@echo "... src/light.i"
	@echo "... src/light.s"
	@echo "... src/material.o"
	@echo "... src/material.i"
	@echo "... src/material.s"
	@echo "... src/mesh.o"
	@echo "... src/mesh.i"
	@echo "... src/mesh.s"
	@echo "... src/ray.o"
	@echo "... src/ray.i"
	@echo "... src/ray.s"
	@echo "... src/resources.o"
	@echo "... src/resources.i"
	@echo "... src/resources.s"
	@echo "... src/rtimage.o"
	@echo "... src/rtimage.i"
	@echo "... src/rtimage.s"
	@echo "... src/texture.o"
	@echo "... src/texture.i"
	@echo "... src/texture.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

